FROM jenkins/slave

USER root

RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get update -y \
    && apt-get install -f -y \
    && dpkg --configure -a \
    && apt-get install -f -y maven openjdk-11-jre-headless